# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dvalovcin\Documents\GitHub\SPEXSidebands-fuzzy\Settings.ui'
#
# Created: Mon May 04 15:58:35 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(521, 569)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.cAGPIB = QtGui.QComboBox(Dialog)
        self.cAGPIB.setObjectName(_fromUtf8("cAGPIB"))
        self.horizontalLayout.addWidget(self.cAGPIB)
        self.horizontalLayout_9.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cSGPIB = QtGui.QComboBox(Dialog)
        self.cSGPIB.setObjectName(_fromUtf8("cSGPIB"))
        self.horizontalLayout_2.addWidget(self.cSGPIB)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.tStartWN = QFNumberEdit(Dialog)
        self.tStartWN.setObjectName(_fromUtf8("tStartWN"))
        self.horizontalLayout_3.addWidget(self.tStartWN)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.tStepWN = QFNumberEdit(Dialog)
        self.tStepWN.setObjectName(_fromUtf8("tStepWN"))
        self.horizontalLayout_3.addWidget(self.tStepWN)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.tEndWN = QFNumberEdit(Dialog)
        self.tEndWN.setObjectName(_fromUtf8("tEndWN"))
        self.horizontalLayout_3.addWidget(self.tEndWN)
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.tAverages = QINumberEdit(Dialog)
        self.tAverages.setObjectName(_fromUtf8("tAverages"))
        self.horizontalLayout_3.addWidget(self.tAverages)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.cPyroCh = QtGui.QComboBox(Dialog)
        self.cPyroCh.setObjectName(_fromUtf8("cPyroCh"))
        self.horizontalLayout_4.addWidget(self.cPyroCh)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.cPMCh = QtGui.QComboBox(Dialog)
        self.cPMCh.setObjectName(_fromUtf8("cPMCh"))
        self.horizontalLayout_4.addWidget(self.cPMCh)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.tNIRP = QFNumberEdit(Dialog)
        self.tNIRP.setObjectName(_fromUtf8("tNIRP"))
        self.horizontalLayout_5.addWidget(self.tNIRP)
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_5.addWidget(self.label_12)
        self.tNIRLam = QFNumberEdit(Dialog)
        self.tNIRLam.setObjectName(_fromUtf8("tNIRLam"))
        self.horizontalLayout_5.addWidget(self.tNIRLam)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_7.addWidget(self.label_13)
        self.tHV = QINumberEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tHV.sizePolicy().hasHeightForWidth())
        self.tHV.setSizePolicy(sizePolicy)
        self.tHV.setObjectName(_fromUtf8("tHV"))
        self.horizontalLayout_7.addWidget(self.tHV)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_6.addWidget(self.label_9)
        self.tFELP = QFNumberEdit(Dialog)
        self.tFELP.setObjectName(_fromUtf8("tFELP"))
        self.horizontalLayout_6.addWidget(self.tFELP)
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_6.addWidget(self.label_15)
        self.tFELLam = QFNumberEdit(Dialog)
        self.tFELLam.setObjectName(_fromUtf8("tFELLam"))
        self.horizontalLayout_6.addWidget(self.tFELLam)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_16 = QtGui.QLabel(Dialog)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_8.addWidget(self.label_16)
        self.tRepRate = QFNumberEdit(Dialog)
        self.tRepRate.setObjectName(_fromUtf8("tRepRate"))
        self.horizontalLayout_8.addWidget(self.tRepRate)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_8.addWidget(self.label_14)
        self.tTemp = QINumberEdit(Dialog)
        self.tTemp.setObjectName(_fromUtf8("tTemp"))
        self.horizontalLayout_8.addWidget(self.tTemp)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_10.addLayout(self.verticalLayout)
        self.tSaveComments = QtGui.QTextEdit(Dialog)
        self.tSaveComments.setObjectName(_fromUtf8("tSaveComments"))
        self.horizontalLayout_10.addWidget(self.tSaveComments)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Settings", None))
        self.label.setText(_translate("Dialog", "Oscilliscope GPIB", None))
        self.cAGPIB.setToolTip(_translate("Dialog", "<html><head/><body><p>USB...</p></body></html>", None))
        self.label_2.setText(_translate("Dialog", "SPEX GPIB", None))
        self.cSGPIB.setToolTip(_translate("Dialog", "<html><head/><body><p>GPIB0::4::INSTR</p></body></html>", None))
        self.label_3.setText(_translate("Dialog", "Starting WN", None))
        self.label_4.setText(_translate("Dialog", "Step", None))
        self.label_5.setText(_translate("Dialog", "Ending WN", None))
        self.label_10.setText(_translate("Dialog", "Average", None))
        self.label_7.setText(_translate("Dialog", "Pyro Channel", None))
        self.label_6.setText(_translate("Dialog", "PM Channel", None))
        self.label_8.setText(_translate("Dialog", "NIR Power (mW)", None))
        self.tNIRP.setText(_translate("Dialog", "0", None))
        self.label_12.setText(_translate("Dialog", "NIR (cm-1)", None))
        self.tNIRLam.setText(_translate("Dialog", "0", None))
        self.label_13.setText(_translate("Dialog", "PM HV", None))
        self.tHV.setToolTip(_translate("Dialog", "<html><head/><body><p>Automatic 10x if 700V</p></body></html>", None))
        self.tHV.setText(_translate("Dialog", "0", None))
        self.label_9.setText(_translate("Dialog", "FEL Power (W)", None))
        self.tFELP.setText(_translate("Dialog", "0", None))
        self.label_15.setText(_translate("Dialog", "FEL  (cm-1)", None))
        self.tFELLam.setText(_translate("Dialog", "0", None))
        self.label_16.setText(_translate("Dialog", "Rep Rate(Hz)", None))
        self.tRepRate.setText(_translate("Dialog", "0.75", None))
        self.label_14.setText(_translate("Dialog", "Temperature", None))
        self.tTemp.setText(_translate("Dialog", "0", None))
        self.label_11.setText(_translate("Dialog", "Save Comments:", None))

from InstsAndQt.customQt import QINumberEdit, QFNumberEdit
