# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dvalovcin\Documents\GitHub\SPEXSidebands-fuzzy\Settings.ui'
#
# Created: Wed Dec 09 15:19:41 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName(_fromUtf8("Settings"))
        Settings.resize(464, 510)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Settings)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(Settings)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.cAGPIB = QtGui.QComboBox(Settings)
        self.cAGPIB.setObjectName(_fromUtf8("cAGPIB"))
        self.horizontalLayout.addWidget(self.cAGPIB)
        self.horizontalLayout_9.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(Settings)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cSGPIB = QtGui.QComboBox(Settings)
        self.cSGPIB.setObjectName(_fromUtf8("cSGPIB"))
        self.horizontalLayout_2.addWidget(self.cSGPIB)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(Settings)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.tStartWN = QFNumberEdit(Settings)
        self.tStartWN.setObjectName(_fromUtf8("tStartWN"))
        self.horizontalLayout_3.addWidget(self.tStartWN)
        self.label_4 = QtGui.QLabel(Settings)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.tStepWN = QFNumberEdit(Settings)
        self.tStepWN.setObjectName(_fromUtf8("tStepWN"))
        self.horizontalLayout_3.addWidget(self.tStepWN)
        self.label_5 = QtGui.QLabel(Settings)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.tEndWN = QFNumberEdit(Settings)
        self.tEndWN.setObjectName(_fromUtf8("tEndWN"))
        self.horizontalLayout_3.addWidget(self.tEndWN)
        self.label_10 = QtGui.QLabel(Settings)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.tAverages = QINumberEdit(Settings)
        self.tAverages.setObjectName(_fromUtf8("tAverages"))
        self.horizontalLayout_3.addWidget(self.tAverages)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_18 = QtGui.QLabel(Settings)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_11.addWidget(self.label_18)
        self.tGotoSB = QFNumberEdit(Settings)
        self.tGotoSB.setObjectName(_fromUtf8("tGotoSB"))
        self.horizontalLayout_11.addWidget(self.tGotoSB)
        self.label_19 = QtGui.QLabel(Settings)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_11.addWidget(self.label_19)
        self.tGotoBound = QFNumberEdit(Settings)
        self.tGotoBound.setObjectName(_fromUtf8("tGotoBound"))
        self.horizontalLayout_11.addWidget(self.tGotoBound)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtGui.QLabel(Settings)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.cPyroCh = QtGui.QComboBox(Settings)
        self.cPyroCh.setObjectName(_fromUtf8("cPyroCh"))
        self.horizontalLayout_4.addWidget(self.cPyroCh)
        self.label_6 = QtGui.QLabel(Settings)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.cPMCh = QtGui.QComboBox(Settings)
        self.cPMCh.setObjectName(_fromUtf8("cPMCh"))
        self.horizontalLayout_4.addWidget(self.cPMCh)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line = QtGui.QFrame(Settings)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_8 = QtGui.QLabel(Settings)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.tNIRP = QFNumberEdit(Settings)
        self.tNIRP.setObjectName(_fromUtf8("tNIRP"))
        self.horizontalLayout_5.addWidget(self.tNIRP)
        self.label_12 = QtGui.QLabel(Settings)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_5.addWidget(self.label_12)
        self.tNIRLam = QFNumberEdit(Settings)
        self.tNIRLam.setObjectName(_fromUtf8("tNIRLam"))
        self.horizontalLayout_5.addWidget(self.tNIRLam)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_13 = QtGui.QLabel(Settings)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_7.addWidget(self.label_13)
        self.cbPMHV = QtGui.QComboBox(Settings)
        self.cbPMHV.setObjectName(_fromUtf8("cbPMHV"))
        self.cbPMHV.addItem(_fromUtf8(""))
        self.cbPMHV.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.cbPMHV)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.cbFilterWhite = QtGui.QCheckBox(Settings)
        self.cbFilterWhite.setObjectName(_fromUtf8("cbFilterWhite"))
        self.horizontalLayout_7.addWidget(self.cbFilterWhite)
        self.cbFilterBlue = QtGui.QCheckBox(Settings)
        self.cbFilterBlue.setObjectName(_fromUtf8("cbFilterBlue"))
        self.horizontalLayout_7.addWidget(self.cbFilterBlue)
        self.cbFilterTriplet = QtGui.QCheckBox(Settings)
        self.cbFilterTriplet.setObjectName(_fromUtf8("cbFilterTriplet"))
        self.horizontalLayout_7.addWidget(self.cbFilterTriplet)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_9 = QtGui.QLabel(Settings)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_6.addWidget(self.label_9)
        self.tFELP = QFNumberEdit(Settings)
        self.tFELP.setObjectName(_fromUtf8("tFELP"))
        self.horizontalLayout_6.addWidget(self.tFELP)
        self.label_15 = QtGui.QLabel(Settings)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_6.addWidget(self.label_15)
        self.tFELLam = QFNumberEdit(Settings)
        self.tFELLam.setObjectName(_fromUtf8("tFELLam"))
        self.horizontalLayout_6.addWidget(self.tFELLam)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_16 = QtGui.QLabel(Settings)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_8.addWidget(self.label_16)
        self.tRepRate = QFNumberEdit(Settings)
        self.tRepRate.setObjectName(_fromUtf8("tRepRate"))
        self.horizontalLayout_8.addWidget(self.tRepRate)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.label_14 = QtGui.QLabel(Settings)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_8.addWidget(self.label_14)
        self.tTemp = QFNumberEdit(Settings)
        self.tTemp.setObjectName(_fromUtf8("tTemp"))
        self.horizontalLayout_8.addWidget(self.tTemp)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_11 = QtGui.QLabel(Settings)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_10.addLayout(self.verticalLayout)
        self.tSaveComments = QtGui.QTextEdit(Settings)
        self.tSaveComments.setObjectName(_fromUtf8("tSaveComments"))
        self.horizontalLayout_10.addWidget(self.tSaveComments)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.cbSaveWaveforms = QtGui.QCheckBox(Settings)
        self.cbSaveWaveforms.setObjectName(_fromUtf8("cbSaveWaveforms"))
        self.verticalLayout_2.addWidget(self.cbSaveWaveforms)
        self.buttonBox = QtGui.QDialogButtonBox(Settings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Settings)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Settings.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Settings.reject)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(_translate("Settings", "Settings", None))
        self.label.setText(_translate("Settings", "Oscilliscope GPIB", None))
        self.cAGPIB.setToolTip(_translate("Settings", "<html><head/><body><p>USB...</p></body></html>", None))
        self.label_2.setText(_translate("Settings", "SPEX GPIB", None))
        self.cSGPIB.setToolTip(_translate("Settings", "<html><head/><body><p>GPIB0::4::INSTR</p></body></html>", None))
        self.label_3.setText(_translate("Settings", "Starting WN", None))
        self.label_4.setText(_translate("Settings", "Step", None))
        self.label_5.setText(_translate("Settings", "Ending WN", None))
        self.label_10.setText(_translate("Settings", "Average", None))
        self.label_18.setText(_translate("Settings", "Go to SB #:", None))
        self.label_19.setText(_translate("Settings", "+/-", None))
        self.label_7.setText(_translate("Settings", "Pyro Channel", None))
        self.label_6.setText(_translate("Settings", "PM Channel", None))
        self.label_8.setText(_translate("Settings", "NIR Power (mW)", None))
        self.tNIRP.setText(_translate("Settings", "0", None))
        self.label_12.setText(_translate("Settings", "NIR (cm-1)", None))
        self.tNIRLam.setText(_translate("Settings", "0", None))
        self.label_13.setText(_translate("Settings", "PM HV", None))
        self.cbPMHV.setItemText(0, _translate("Settings", "700", None))
        self.cbPMHV.setItemText(1, _translate("Settings", "1000", None))
        self.cbFilterWhite.setText(_translate("Settings", "White", None))
        self.cbFilterBlue.setText(_translate("Settings", "Blue", None))
        self.cbFilterTriplet.setText(_translate("Settings", "Triplet", None))
        self.label_9.setText(_translate("Settings", "FEL Power (W)", None))
        self.tFELP.setText(_translate("Settings", "0", None))
        self.label_15.setText(_translate("Settings", "FEL  (cm-1)", None))
        self.tFELLam.setText(_translate("Settings", "0", None))
        self.label_16.setText(_translate("Settings", "Rep Rate(Hz)", None))
        self.tRepRate.setText(_translate("Settings", "1.07", None))
        self.label_14.setText(_translate("Settings", "Temperature", None))
        self.tTemp.setText(_translate("Settings", "0", None))
        self.label_11.setText(_translate("Settings", "Save Comments:", None))
        self.cbSaveWaveforms.setText(_translate("Settings", "Save waveforms instead of boxcars", None))

from InstsAndQt.customQt import QINumberEdit, QFNumberEdit
