# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clickablePlotSettings.ui'
#
# Created: Fri Nov  6 08:21:19 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig)

class Ui_LineSettingsDialog(object):
    def setupUi(self, LineSettingsDialog):
        LineSettingsDialog.setObjectName("LineSettingsDialog")
        LineSettingsDialog.resize(561, 466)
        self.buttonBox = QtWidgets.QDialogButtonBox(LineSettingsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(60, 380, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lwCurves = QtWidgets.QListWidget(LineSettingsDialog)
        self.lwCurves.setGeometry(QtCore.QRect(20, 10, 131, 201))
        self.lwCurves.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lwCurves.setObjectName("lwCurves")
        self.twCurveSettings = QtWidgets.QTabWidget(LineSettingsDialog)
        self.twCurveSettings.setGeometry(QtCore.QRect(180, 20, 415, 246))
        self.twCurveSettings.setObjectName("twCurveSettings")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sbLineWidth = SpinBox(self.groupBox)
        self.sbLineWidth.setObjectName("sbLineWidth")
        self.horizontalLayout.addWidget(self.sbLineWidth)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbLineStyle = QtWidgets.QComboBox(self.groupBox_3)
        self.cbLineStyle.setObjectName("cbLineStyle")
        self.cbLineStyle.addItem("")
        self.cbLineStyle.addItem("")
        self.cbLineStyle.addItem("")
        self.cbLineStyle.addItem("")
        self.cbLineStyle.addItem("")
        self.cbLineStyle.addItem("")
        self.horizontalLayout_2.addWidget(self.cbLineStyle)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.colLine = ColorButton(self.groupBox_4)
        self.colLine.setObjectName("colLine")
        self.horizontalLayout_3.addWidget(self.colLine)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sbMarkerSize = SpinBox(self.groupBox_2)
        self.sbMarkerSize.setObjectName("sbMarkerSize")
        self.horizontalLayout_5.addWidget(self.sbMarkerSize)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cbMarkerStyle = QtWidgets.QComboBox(self.groupBox_6)
        self.cbMarkerStyle.setObjectName("cbMarkerStyle")
        self.cbMarkerStyle.addItem("")
        self.cbMarkerStyle.addItem("")
        self.cbMarkerStyle.addItem("")
        self.cbMarkerStyle.addItem("")
        self.cbMarkerStyle.addItem("")
        self.cbMarkerStyle.addItem("")
        self.cbMarkerStyle.addItem("")
        self.horizontalLayout_6.addWidget(self.cbMarkerStyle)
        self.horizontalLayout_4.addWidget(self.groupBox_6)
        self.colMarker = ColorButton(self.groupBox_5)
        self.colMarker.setObjectName("colMarker")
        self.horizontalLayout_4.addWidget(self.colMarker)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.twCurveSettings.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tXOffset = QtWidgets.QLineEdit(self.tab_2)
        self.tXOffset.setGeometry(QtCore.QRect(142, 40, 101, 21))
        self.tXOffset.setObjectName("tXOffset")
        self.tYOffset = QtWidgets.QLineEdit(self.tab_2)
        self.tYOffset.setGeometry(QtCore.QRect(192, 100, 81, 21))
        self.tYOffset.setObjectName("tYOffset")
        self.twCurveSettings.addTab(self.tab_2, "")

        self.retranslateUi(LineSettingsDialog)
        self.twCurveSettings.setCurrentIndex(0)
        self.buttonBox.accepted.connect(LineSettingsDialog.accept)
        self.buttonBox.rejected.connect(LineSettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(LineSettingsDialog)

    def retranslateUi(self, LineSettingsDialog):
        LineSettingsDialog.setWindowTitle(_translate("LineSettingsDialog", "Dialog", None))
        self.groupBox_4.setTitle(_translate("LineSettingsDialog", "Line", None))
        self.groupBox.setTitle(_translate("LineSettingsDialog", "Linewidth", None))
        self.groupBox_3.setTitle(_translate("LineSettingsDialog", "Style", None))
        self.cbLineStyle.setItemText(0, _translate("LineSettingsDialog", "None", None))
        self.cbLineStyle.setItemText(1, _translate("LineSettingsDialog", "Solid", None))
        self.cbLineStyle.setItemText(2, _translate("LineSettingsDialog", "Dashed", None))
        self.cbLineStyle.setItemText(3, _translate("LineSettingsDialog", "Dotted", None))
        self.cbLineStyle.setItemText(4, _translate("LineSettingsDialog", "Dash Dot", None))
        self.cbLineStyle.setItemText(5, _translate("LineSettingsDialog", "Dash Dot Dot", None))
        self.colLine.setText(_translate("LineSettingsDialog", "PushButton", None))
        self.groupBox_5.setTitle(_translate("LineSettingsDialog", "Marker", None))
        self.groupBox_2.setTitle(_translate("LineSettingsDialog", "Size", None))
        self.groupBox_6.setTitle(_translate("LineSettingsDialog", "Style", None))
        self.cbMarkerStyle.setItemText(0, _translate("LineSettingsDialog", "None", None))
        self.cbMarkerStyle.setItemText(1, _translate("LineSettingsDialog", "o", None))
        self.cbMarkerStyle.setItemText(2, _translate("LineSettingsDialog", "s", None))
        self.cbMarkerStyle.setItemText(3, _translate("LineSettingsDialog", "t", None))
        self.cbMarkerStyle.setItemText(4, _translate("LineSettingsDialog", "d", None))
        self.cbMarkerStyle.setItemText(5, _translate("LineSettingsDialog", "+", None))
        self.cbMarkerStyle.setItemText(6, _translate("LineSettingsDialog", "x", None))
        self.colMarker.setText(_translate("LineSettingsDialog", "PushButton", None))
        self.twCurveSettings.setTabText(self.twCurveSettings.indexOf(self.tab), _translate("LineSettingsDialog", "Line Style", None))
        self.twCurveSettings.setTabText(self.twCurveSettings.indexOf(self.tab_2), _translate("LineSettingsDialog", "Offset", None))

from pyqtgraph import SpinBox, ColorButton

