# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dvalovcin\Documents\GitHub\SPEXSidebands-fuzzy\UIs\MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(747, 683)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/test/SPEXIcon.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gSignal = PlotWidget(self.layoutWidget)
        self.gSignal.setObjectName(_fromUtf8("gSignal"))
        self.verticalLayout_2.addWidget(self.gSignal)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tPmBgEn = QFNumberEdit(self.layoutWidget)
        self.tPmBgEn.setObjectName(_fromUtf8("tPmBgEn"))
        self.gridLayout_2.addWidget(self.tPmBgEn, 1, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 1, 4, 1, 1)
        self.tPmBgSt = QFNumberEdit(self.layoutWidget)
        self.tPmBgSt.setObjectName(_fromUtf8("tPmBgSt"))
        self.gridLayout_2.addWidget(self.tPmBgSt, 0, 3, 1, 1)
        self.tPmSgEn = QFNumberEdit(self.layoutWidget)
        self.tPmSgEn.setObjectName(_fromUtf8("tPmSgEn"))
        self.gridLayout_2.addWidget(self.tPmSgEn, 1, 5, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 1, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.bInitPMT = QtGui.QPushButton(self.layoutWidget)
        self.bInitPMT.setObjectName(_fromUtf8("bInitPMT"))
        self.gridLayout_2.addWidget(self.bInitPMT, 1, 1, 1, 1)
        self.tPmSgSt = QFNumberEdit(self.layoutWidget)
        self.tPmSgSt.setObjectName(_fromUtf8("tPmSgSt"))
        self.gridLayout_2.addWidget(self.tPmSgSt, 0, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_5.addWidget(self.splitter)
        self.verticalLayout_5.setStretch(0, 100)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tabPC = QtGui.QWidget()
        self.tabPC.setObjectName(_fromUtf8("tabPC"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabPC)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gPC = DoubleYPlot(self.tabPC)
        self.gPC.setObjectName(_fromUtf8("gPC"))
        self.verticalLayout_4.addWidget(self.gPC)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_4 = QtGui.QGroupBox(self.tabPC)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_8.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.tPCThreshold = QFNumberEdit(self.groupBox_4)
        self.tPCThreshold.setObjectName(_fromUtf8("tPCThreshold"))
        self.horizontalLayout_8.addWidget(self.tPCThreshold)
        self.gridLayout_3.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.tabPC, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gScan = ClickablePlotWidget(self.tab_2)
        self.gScan.setObjectName(_fromUtf8("gScan"))
        self.verticalLayout_3.addWidget(self.gScan)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.bClearScan = QtGui.QPushButton(self.tab_2)
        self.bClearScan.setObjectName(_fromUtf8("bClearScan"))
        self.horizontalLayout_4.addWidget(self.bClearScan)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.tSeries = QtGui.QLineEdit(self.groupBox_3)
        self.tSeries.setPlaceholderText(_fromUtf8(""))
        self.tSeries.setObjectName(_fromUtf8("tSeries"))
        self.horizontalLayout_7.addWidget(self.tSeries)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.tSaveName = QtGui.QLineEdit(self.groupBox_2)
        self.tSaveName.setObjectName(_fromUtf8("tSaveName"))
        self.horizontalLayout_6.addWidget(self.tSaveName)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.bChooseDirectory = QtGui.QPushButton(self.centralwidget)
        self.bChooseDirectory.setObjectName(_fromUtf8("bChooseDirectory"))
        self.horizontalLayout.addWidget(self.bChooseDirectory)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tSidebandNumber = QtGui.QLineEdit(self.groupBox)
        self.tSidebandNumber.setObjectName(_fromUtf8("tSidebandNumber"))
        self.horizontalLayout_5.addWidget(self.tSidebandNumber)
        self.horizontalLayout.addWidget(self.groupBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.bAbort = QtGui.QPushButton(self.centralwidget)
        self.bAbort.setObjectName(_fromUtf8("bAbort"))
        self.gridLayout.addWidget(self.bAbort, 1, 2, 1, 1)
        self.bQuickStart = QtGui.QPushButton(self.centralwidget)
        self.bQuickStart.setObjectName(_fromUtf8("bQuickStart"))
        self.gridLayout.addWidget(self.bQuickStart, 0, 2, 1, 1)
        self.bSaveWaveforms = QtGui.QPushButton(self.centralwidget)
        self.bSaveWaveforms.setObjectName(_fromUtf8("bSaveWaveforms"))
        self.gridLayout.addWidget(self.bSaveWaveforms, 1, 0, 1, 1)
        self.bPause = QtGui.QPushButton(self.centralwidget)
        self.bPause.setCheckable(True)
        self.bPause.setObjectName(_fromUtf8("bPause"))
        self.gridLayout.addWidget(self.bPause, 0, 0, 1, 1)
        self.bStart = QtGui.QPushButton(self.centralwidget)
        self.bStart.setObjectName(_fromUtf8("bStart"))
        self.gridLayout.addWidget(self.bStart, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 747, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSPEX = QtGui.QMenu(self.menubar)
        self.menuSPEX.setObjectName(_fromUtf8("menuSPEX"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.mFileSettings = QtGui.QAction(MainWindow)
        self.mFileSettings.setObjectName(_fromUtf8("mFileSettings"))
        self.mFileExit = QtGui.QAction(MainWindow)
        self.mFileExit.setObjectName(_fromUtf8("mFileExit"))
        self.actionInitialize = QtGui.QAction(MainWindow)
        self.actionInitialize.setObjectName(_fromUtf8("actionInitialize"))
        self.actionGoto_Wavenumber = QtGui.QAction(MainWindow)
        self.actionGoto_Wavenumber.setObjectName(_fromUtf8("actionGoto_Wavenumber"))
        self.mSpexOpen = QtGui.QAction(MainWindow)
        self.mSpexOpen.setObjectName(_fromUtf8("mSpexOpen"))
        self.menuFile.addAction(self.mFileSettings)
        self.menuFile.addAction(self.mFileExit)
        self.menuSPEX.addAction(self.mSpexOpen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSPEX.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tPmBgSt, self.tPmBgEn)
        MainWindow.setTabOrder(self.tPmBgEn, self.tPmSgSt)
        MainWindow.setTabOrder(self.tPmSgSt, self.tPmSgEn)
        MainWindow.setTabOrder(self.tPmSgEn, self.bChooseDirectory)
        MainWindow.setTabOrder(self.bChooseDirectory, self.bPause)
        MainWindow.setTabOrder(self.bPause, self.bQuickStart)
        MainWindow.setTabOrder(self.bQuickStart, self.bSaveWaveforms)
        MainWindow.setTabOrder(self.bSaveWaveforms, self.bAbort)
        MainWindow.setTabOrder(self.bAbort, self.gSignal)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Sideband Measurements", None))
        self.tPmBgEn.setText(_translate("MainWindow", "0", None))
        self.label_11.setText(_translate("MainWindow", "PMT Sig En", None))
        self.tPmBgSt.setText(_translate("MainWindow", "0", None))
        self.tPmSgEn.setText(_translate("MainWindow", "0", None))
        self.label_10.setText(_translate("MainWindow", "PMT BG End", None))
        self.label_6.setText(_translate("MainWindow", "PMT Sig Start", None))
        self.label_5.setText(_translate("MainWindow", "PMT BG Start", None))
        self.bInitPMT.setText(_translate("MainWindow", "Init PMT", None))
        self.tPmSgSt.setText(_translate("MainWindow", "0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Experimental Settings", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "PC Threshold", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPC), _translate("MainWindow", "Photon Counting", None))
        self.bClearScan.setText(_translate("MainWindow", "Clear", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Scan", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Series", None))
        self.tSeries.setToolTip(_translate("MainWindow", "{NIRP, NIRL, FELP, FELL, TEMP, PMHV}", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Save Name", None))
        self.bChooseDirectory.setText(_translate("MainWindow", "Choose Directory", None))
        self.groupBox.setTitle(_translate("MainWindow", "Sideband Number", None))
        self.bAbort.setText(_translate("MainWindow", "Abort", None))
        self.bQuickStart.setText(_translate("MainWindow", "Quick Start", None))
        self.bSaveWaveforms.setText(_translate("MainWindow", "Save Waveforms", None))
        self.bPause.setText(_translate("MainWindow", "Pause", None))
        self.bStart.setText(_translate("MainWindow", "Start", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSPEX.setTitle(_translate("MainWindow", "SPEX", None))
        self.mFileSettings.setText(_translate("MainWindow", "Settings", None))
        self.mFileExit.setText(_translate("MainWindow", "Exit", None))
        self.actionInitialize.setText(_translate("MainWindow", "Initialize...", None))
        self.actionGoto_Wavenumber.setText(_translate("MainWindow", "Goto Wavenumber...", None))
        self.mSpexOpen.setText(_translate("MainWindow", "Open SPEX Settings", None))

from InstsAndQt.customQt import DoubleYPlot, QFNumberEdit
from .clickablePlotWidget import ClickablePlotWidget
from pyqtgraph import PlotWidget
from . import resources_rc
