# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dvalovcin\Documents\GitHub\SPEXSidebands-fuzzy\UIs\MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(747, 683)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/test/SPEXIcon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter = QtWidgets.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gSignal = PlotWidget(self.layoutWidget)
        self.gSignal.setObjectName("gSignal")
        self.verticalLayout_2.addWidget(self.gSignal)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tPmBgEn = QFNumberEdit(self.layoutWidget)
        self.tPmBgEn.setObjectName("tPmBgEn")
        self.gridLayout_2.addWidget(self.tPmBgEn, 1, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 4, 1, 1)
        self.tPmBgSt = QFNumberEdit(self.layoutWidget)
        self.tPmBgSt.setObjectName("tPmBgSt")
        self.gridLayout_2.addWidget(self.tPmBgSt, 0, 3, 1, 1)
        self.tPmSgEn = QFNumberEdit(self.layoutWidget)
        self.tPmSgEn.setObjectName("tPmSgEn")
        self.gridLayout_2.addWidget(self.tPmSgEn, 1, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.bInitPMT = QtWidgets.QPushButton(self.layoutWidget)
        self.bInitPMT.setObjectName("bInitPMT")
        self.gridLayout_2.addWidget(self.bInitPMT, 1, 1, 1, 1)
        self.tPmSgSt = QFNumberEdit(self.layoutWidget)
        self.tPmSgSt.setObjectName("tPmSgSt")
        self.gridLayout_2.addWidget(self.tPmSgSt, 0, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_5.addWidget(self.splitter)
        self.verticalLayout_5.setStretch(0, 100)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab, "")
        self.tabPC = QtWidgets.QWidget()
        self.tabPC.setObjectName("tabPC")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabPC)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gPC = DoubleYPlot(self.tabPC)
        self.gPC.setObjectName("gPC")
        self.verticalLayout_4.addWidget(self.gPC)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabPC)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_8.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tPCThreshold = QFNumberEdit(self.groupBox_4)
        self.tPCThreshold.setObjectName("tPCThreshold")
        self.horizontalLayout_8.addWidget(self.tPCThreshold)
        self.gridLayout_3.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.tabPC, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gScan = ClickablePlotWidget(self.tab_2)
        self.gScan.setObjectName("gScan")
        self.verticalLayout_3.addWidget(self.gScan)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.bClearScan = QtWidgets.QPushButton(self.tab_2)
        self.bClearScan.setObjectName("bClearScan")
        self.horizontalLayout_4.addWidget(self.bClearScan)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tSeries = QtWidgets.QLineEdit(self.groupBox_3)
        self.tSeries.setPlaceholderText("")
        self.tSeries.setObjectName("tSeries")
        self.horizontalLayout_7.addWidget(self.tSeries)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tSaveName = QtWidgets.QLineEdit(self.groupBox_2)
        self.tSaveName.setObjectName("tSaveName")
        self.horizontalLayout_6.addWidget(self.tSaveName)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.bChooseDirectory = QtWidgets.QPushButton(self.centralwidget)
        self.bChooseDirectory.setObjectName("bChooseDirectory")
        self.horizontalLayout.addWidget(self.bChooseDirectory)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tSidebandNumber = QtWidgets.QLineEdit(self.groupBox)
        self.tSidebandNumber.setObjectName("tSidebandNumber")
        self.horizontalLayout_5.addWidget(self.tSidebandNumber)
        self.horizontalLayout.addWidget(self.groupBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bAbort = QtWidgets.QPushButton(self.centralwidget)
        self.bAbort.setObjectName("bAbort")
        self.gridLayout.addWidget(self.bAbort, 1, 2, 1, 1)
        self.bQuickStart = QtWidgets.QPushButton(self.centralwidget)
        self.bQuickStart.setObjectName("bQuickStart")
        self.gridLayout.addWidget(self.bQuickStart, 0, 2, 1, 1)
        self.bSaveWaveforms = QtWidgets.QPushButton(self.centralwidget)
        self.bSaveWaveforms.setObjectName("bSaveWaveforms")
        self.gridLayout.addWidget(self.bSaveWaveforms, 1, 0, 1, 1)
        self.bPause = QtWidgets.QPushButton(self.centralwidget)
        self.bPause.setCheckable(True)
        self.bPause.setObjectName("bPause")
        self.gridLayout.addWidget(self.bPause, 0, 0, 1, 1)
        self.bStart = QtWidgets.QPushButton(self.centralwidget)
        self.bStart.setObjectName("bStart")
        self.gridLayout.addWidget(self.bStart, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 747, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSPEX = QtWidgets.QMenu(self.menubar)
        self.menuSPEX.setObjectName("menuSPEX")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.mFileSettings = QtWidgets.QAction(MainWindow)
        self.mFileSettings.setObjectName("mFileSettings")
        self.mFileExit = QtWidgets.QAction(MainWindow)
        self.mFileExit.setObjectName("mFileExit")
        self.actionInitialize = QtWidgets.QAction(MainWindow)
        self.actionInitialize.setObjectName("actionInitialize")
        self.actionGoto_Wavenumber = QtWidgets.QAction(MainWindow)
        self.actionGoto_Wavenumber.setObjectName("actionGoto_Wavenumber")
        self.mSpexOpen = QtWidgets.QAction(MainWindow)
        self.mSpexOpen.setObjectName("mSpexOpen")
        self.menuFile.addAction(self.mFileSettings)
        self.menuFile.addAction(self.mFileExit)
        self.menuSPEX.addAction(self.mSpexOpen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSPEX.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tPmBgSt, self.tPmBgEn)
        MainWindow.setTabOrder(self.tPmBgEn, self.tPmSgSt)
        MainWindow.setTabOrder(self.tPmSgSt, self.tPmSgEn)
        MainWindow.setTabOrder(self.tPmSgEn, self.bChooseDirectory)
        MainWindow.setTabOrder(self.bChooseDirectory, self.bPause)
        MainWindow.setTabOrder(self.bPause, self.bQuickStart)
        MainWindow.setTabOrder(self.bQuickStart, self.bSaveWaveforms)
        MainWindow.setTabOrder(self.bSaveWaveforms, self.bAbort)
        MainWindow.setTabOrder(self.bAbort, self.gSignal)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Sideband Measurements", None))
        self.tPmBgEn.setText(_translate("MainWindow", "0", None))
        self.label_11.setText(_translate("MainWindow", "PMT Sig En", None))
        self.tPmBgSt.setText(_translate("MainWindow", "0", None))
        self.tPmSgEn.setText(_translate("MainWindow", "0", None))
        self.label_10.setText(_translate("MainWindow", "PMT BG End", None))
        self.label_6.setText(_translate("MainWindow", "PMT Sig Start", None))
        self.label_5.setText(_translate("MainWindow", "PMT BG Start", None))
        self.bInitPMT.setText(_translate("MainWindow", "Init PMT", None))
        self.tPmSgSt.setText(_translate("MainWindow", "0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Experimental Settings", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "PC Threshold", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPC), _translate("MainWindow", "Photon Counting", None))
        self.bClearScan.setText(_translate("MainWindow", "Clear", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Scan", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Series", None))
        self.tSeries.setToolTip(_translate("MainWindow", "{NIRP, NIRL, FELP, FELL, TEMP, PMHV}", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Save Name", None))
        self.bChooseDirectory.setText(_translate("MainWindow", "Choose Directory", None))
        self.groupBox.setTitle(_translate("MainWindow", "Sideband Number", None))
        self.bAbort.setText(_translate("MainWindow", "Abort", None))
        self.bQuickStart.setText(_translate("MainWindow", "Quick Start", None))
        self.bSaveWaveforms.setText(_translate("MainWindow", "Save Waveforms", None))
        self.bPause.setText(_translate("MainWindow", "Pause", None))
        self.bStart.setText(_translate("MainWindow", "Start", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSPEX.setTitle(_translate("MainWindow", "SPEX", None))
        self.mFileSettings.setText(_translate("MainWindow", "Settings", None))
        self.mFileExit.setText(_translate("MainWindow", "Exit", None))
        self.actionInitialize.setText(_translate("MainWindow", "Initialize...", None))
        self.actionGoto_Wavenumber.setText(_translate("MainWindow", "Goto Wavenumber...", None))
        self.mSpexOpen.setText(_translate("MainWindow", "Open SPEX Settings", None))

from InstsAndQt.customQt import DoubleYPlot, QFNumberEdit

from .clickablePlotWidget import ClickablePlotWidget

from pyqtgraph import PlotWidget

from . import resources_rc

