# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dvalovcin\Documents\GitHub\SPEXSidebands-fuzzy\UIs\Settings.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig)

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(464, 510)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Settings)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cAGPIB = QtWidgets.QComboBox(Settings)
        self.cAGPIB.setObjectName("cAGPIB")
        self.horizontalLayout.addWidget(self.cAGPIB)
        self.horizontalLayout_9.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Settings)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cSGPIB = QtWidgets.QComboBox(Settings)
        self.cSGPIB.setObjectName("cSGPIB")
        self.horizontalLayout_2.addWidget(self.cSGPIB)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lStartWN = QtWidgets.QLabel(Settings)
        self.lStartWN.setObjectName("lStartWN")
        self.horizontalLayout_3.addWidget(self.lStartWN)
        self.tStartWN = QFNumberEdit(Settings)
        self.tStartWN.setObjectName("tStartWN")
        self.horizontalLayout_3.addWidget(self.tStartWN)
        self.lStepWN = QtWidgets.QLabel(Settings)
        self.lStepWN.setObjectName("lStepWN")
        self.horizontalLayout_3.addWidget(self.lStepWN)
        self.tStepWN = QFNumberEdit(Settings)
        self.tStepWN.setObjectName("tStepWN")
        self.horizontalLayout_3.addWidget(self.tStepWN)
        self.lEndWN = QtWidgets.QLabel(Settings)
        self.lEndWN.setObjectName("lEndWN")
        self.horizontalLayout_3.addWidget(self.lEndWN)
        self.tEndWN = QFNumberEdit(Settings)
        self.tEndWN.setObjectName("tEndWN")
        self.horizontalLayout_3.addWidget(self.tEndWN)
        self.label_10 = QtWidgets.QLabel(Settings)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.tAverages = QINumberEdit(Settings)
        self.tAverages.setObjectName("tAverages")
        self.horizontalLayout_3.addWidget(self.tAverages)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_18 = QtWidgets.QLabel(Settings)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_11.addWidget(self.label_18)
        self.tGotoSB = QFNumberEdit(Settings)
        self.tGotoSB.setObjectName("tGotoSB")
        self.horizontalLayout_11.addWidget(self.tGotoSB)
        self.label_19 = QtWidgets.QLabel(Settings)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_11.addWidget(self.label_19)
        self.tGotoBound = QFNumberEdit(Settings)
        self.tGotoBound.setObjectName("tGotoBound")
        self.horizontalLayout_11.addWidget(self.tGotoBound)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(Settings)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.cPyroCh = QtWidgets.QComboBox(Settings)
        self.cPyroCh.setObjectName("cPyroCh")
        self.horizontalLayout_4.addWidget(self.cPyroCh)
        self.label_6 = QtWidgets.QLabel(Settings)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.cPMCh = QtWidgets.QComboBox(Settings)
        self.cPMCh.setObjectName("cPMCh")
        self.horizontalLayout_4.addWidget(self.cPMCh)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(Settings)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(Settings)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.tNIRP = QFNumberEdit(Settings)
        self.tNIRP.setObjectName("tNIRP")
        self.horizontalLayout_5.addWidget(self.tNIRP)
        self.label_12 = QtWidgets.QLabel(Settings)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.tNIRLam = QFNumberEdit(Settings)
        self.tNIRLam.setObjectName("tNIRLam")
        self.horizontalLayout_5.addWidget(self.tNIRLam)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(Settings)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.cbPMHV = QtWidgets.QComboBox(Settings)
        self.cbPMHV.setObjectName("cbPMHV")
        self.cbPMHV.addItem("")
        self.cbPMHV.addItem("")
        self.horizontalLayout_7.addWidget(self.cbPMHV)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.cbFilterWhite = QtWidgets.QCheckBox(Settings)
        self.cbFilterWhite.setObjectName("cbFilterWhite")
        self.horizontalLayout_7.addWidget(self.cbFilterWhite)
        self.cbFilterBlue = QtWidgets.QCheckBox(Settings)
        self.cbFilterBlue.setObjectName("cbFilterBlue")
        self.horizontalLayout_7.addWidget(self.cbFilterBlue)
        self.cbFilterTriplet = QtWidgets.QCheckBox(Settings)
        self.cbFilterTriplet.setObjectName("cbFilterTriplet")
        self.horizontalLayout_7.addWidget(self.cbFilterTriplet)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(Settings)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.tFELP = QFNumberEdit(Settings)
        self.tFELP.setObjectName("tFELP")
        self.horizontalLayout_6.addWidget(self.tFELP)
        self.label_15 = QtWidgets.QLabel(Settings)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_6.addWidget(self.label_15)
        self.tFELLam = QFNumberEdit(Settings)
        self.tFELLam.setObjectName("tFELLam")
        self.horizontalLayout_6.addWidget(self.tFELLam)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_16 = QtWidgets.QLabel(Settings)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.tRepRate = QFNumberEdit(Settings)
        self.tRepRate.setObjectName("tRepRate")
        self.horizontalLayout_8.addWidget(self.tRepRate)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.label_14 = QtWidgets.QLabel(Settings)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_8.addWidget(self.label_14)
        self.tTemp = QFNumberEdit(Settings)
        self.tTemp.setObjectName("tTemp")
        self.horizontalLayout_8.addWidget(self.tTemp)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_11 = QtWidgets.QLabel(Settings)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_10.addLayout(self.verticalLayout)
        self.tSaveComments = QtWidgets.QTextEdit(Settings)
        self.tSaveComments.setObjectName("tSaveComments")
        self.horizontalLayout_10.addWidget(self.tSaveComments)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.cbSaveWaveforms = QtWidgets.QCheckBox(Settings)
        self.cbSaveWaveforms.setObjectName("cbSaveWaveforms")
        self.horizontalLayout_12.addWidget(self.cbSaveWaveforms)
        self.cbPC = QtWidgets.QCheckBox(Settings)
        self.cbPC.setEnabled(False)
        self.cbPC.setObjectName("cbPC")
        self.horizontalLayout_12.addWidget(self.cbPC)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Settings)
        self.buttonBox.accepted.connect(Settings.accept)
        self.buttonBox.rejected.connect(Settings.reject)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(_translate("Settings", "Settings", None))
        self.label.setText(_translate("Settings", "Oscilliscope GPIB", None))
        self.cAGPIB.setToolTip(_translate("Settings", "<html><head/><body><p>USB...</p></body></html>", None))
        self.label_2.setText(_translate("Settings", "SPEX GPIB", None))
        self.cSGPIB.setToolTip(_translate("Settings", "<html><head/><body><p>GPIB0::4::INSTR</p></body></html>", None))
        self.lStartWN.setText(_translate("Settings", "Starting WN", None))
        self.lStepWN.setText(_translate("Settings", "Step", None))
        self.lEndWN.setText(_translate("Settings", "Ending WN", None))
        self.label_10.setText(_translate("Settings", "Average", None))
        self.label_18.setText(_translate("Settings", "Go to SB #:", None))
        self.label_19.setText(_translate("Settings", "+/-", None))
        self.label_7.setText(_translate("Settings", "Pyro Channel", None))
        self.label_6.setText(_translate("Settings", "PM Channel", None))
        self.label_8.setText(_translate("Settings", "NIR Power (mW)", None))
        self.tNIRP.setText(_translate("Settings", "0", None))
        self.label_12.setText(_translate("Settings", "NIR (cm-1)", None))
        self.tNIRLam.setText(_translate("Settings", "0", None))
        self.label_13.setText(_translate("Settings", "PM HV", None))
        self.cbPMHV.setItemText(0, _translate("Settings", "700", None))
        self.cbPMHV.setItemText(1, _translate("Settings", "1000", None))
        self.cbFilterWhite.setText(_translate("Settings", "White", None))
        self.cbFilterBlue.setText(_translate("Settings", "Blue", None))
        self.cbFilterTriplet.setText(_translate("Settings", "Triplet", None))
        self.label_9.setText(_translate("Settings", "FEL Energy (mJ)", None))
        self.tFELP.setText(_translate("Settings", "0", None))
        self.label_15.setText(_translate("Settings", "FEL  (cm-1)", None))
        self.tFELLam.setText(_translate("Settings", "0", None))
        self.label_16.setText(_translate("Settings", "Rep Rate(Hz)", None))
        self.tRepRate.setText(_translate("Settings", "1.07", None))
        self.label_14.setText(_translate("Settings", "Temperature", None))
        self.tTemp.setText(_translate("Settings", "0", None))
        self.label_11.setText(_translate("Settings", "Save Comments:", None))
        self.cbSaveWaveforms.setText(_translate("Settings", "Save waveforms instead of boxcars", None))
        self.cbPC.setText(_translate("Settings", "Photon Count Waveforms", None))

from InstsAndQt.customQt import QFNumberEdit, QINumberEdit

